/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/64f1a714fe61576b46f27ca2.glb -o src/components/Avatar.jsx -k -r public
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { button, useControls } from "leva";
import React, { useEffect, useRef, useState } from "react";

import * as THREE from "three";
import { useChat } from "../hooks/useChat";

const facialExpressions = {
  default: {},
  smile: {
    browInnerUp: 0.17,
    eyeSquintLeft: 0.4,
    eyeSquintRight: 0.44,
    noseSneerLeft: 0.1700000727403593,
    noseSneerRight: 0.14000002836874015,
    mouthPressLeft: 0.61,
    mouthPressRight: 0.41000000000000003,
  },
  funnyFace: {
    jawLeft: 0.63,
    mouthPucker: 0.53,
    noseSneerLeft: 1,
    noseSneerRight: 0.39,
    mouthLeft: 1,
    eyeLookUpLeft: 1,
    eyeLookUpRight: 1,
    cheekPuff: 0.9999924982764238,
    mouthDimpleLeft: 0.414743888682652,
    mouthRollLower: 0.32,
    mouthSmileLeft: 0.35499733688813034,
    mouthSmileRight: 0.35499733688813034,
  },
  sad: {
    mouthFrownLeft: 1,
    mouthFrownRight: 1,
    mouthShrugLower: 0.78341,
    browInnerUp: 0.452,
    eyeSquintLeft: 0.72,
    eyeSquintRight: 0.75,
    eyeLookDownLeft: 0.5,
    eyeLookDownRight: 0.5,
    jawForward: 1,
  },
  surprised: {
    eyeWideLeft: 0.5,
    eyeWideRight: 0.5,
    jawOpen: 0.351,
    mouthFunnel: 1,
    browInnerUp: 1,
  },
  angry: {
    browDownLeft: 1,
    browDownRight: 1,
    eyeSquintLeft: 1,
    eyeSquintRight: 1,
    jawForward: 1,
    jawLeft: 1,
    mouthShrugLower: 1,
    noseSneerLeft: 1,
    noseSneerRight: 0.42,
    eyeLookDownLeft: 0.16,
    eyeLookDownRight: 0.16,
    cheekSquintLeft: 1,
    cheekSquintRight: 1,
    mouthClose: 0.23,
    mouthFunnel: 0.63,
    mouthDimpleRight: 1,
  },
  crazy: {
    browInnerUp: 0.9,
    jawForward: 1,
    noseSneerLeft: 0.5700000000000001,
    noseSneerRight: 0.51,
    eyeLookDownLeft: 0.39435766259644545,
    eyeLookUpRight: 0.4039761421719682,
    eyeLookInLeft: 0.9618479575523053,
    eyeLookInRight: 0.9618479575523053,
    jawOpen: 0.9618479575523053,
    mouthDimpleLeft: 0.9618479575523053,
    mouthDimpleRight: 0.9618479575523053,
    mouthStretchLeft: 0.27893590769016857,
    mouthStretchRight: 0.2885543872656917,
    mouthSmileLeft: 0.5578718153803371,
    mouthSmileRight: 0.38473918302092225,
    tongueOut: 0.9618479575523053,
  },
};

const corresponding = {
  A: "viseme_PP",
  B: "viseme_kk",
  C: "viseme_I",
  D: "viseme_AA",
  E: "viseme_O",
  F: "viseme_U",
  G: "viseme_FF",
  H: "viseme_TH",
  X: "viseme_PP",
};

let setupMode = false;

export function Avatar(props) {
  const { nodes, materials, scene } = useGLTF(
    "/models/64f1a714fe61576b46f27ca2.glb"
  );

  const { message, onMessagePlayed, chat } = useChat();

  const [lipsync, setLipsync] = useState();

  useEffect(() => {
    console.log(message);
    if (!message) {
      setAnimation("Idle");
      return;
    }
    setAnimation(message.animation);
    setFacialExpression(message.facialExpression);
    setLipsync(message.lipsync);
    const audio = new Audio("data:audio/mp3;base64," + message.audio);
    audio.play();
    setAudio(audio);
    audio.onended = onMessagePlayed;
  }, [message]);

  const { animations } = useGLTF("/models/animations.glb");

  const group = useRef();
  const { actions, mixer } = useAnimations(animations, group);
  const [animation, setAnimation] = useState(
    animations.find((a) => a.name === "Idle") ? "Idle" : animations[0].name // Check if Idle animation exists otherwise use first animation
  );
  useEffect(() => {
    const currentAction = actions[animation];
    if (currentAction) {
      currentAction.reset().fadeIn(mixer.stats.actions.inUse === 0 ? 0 : 0.5).play();
      return () => currentAction.fadeOut(0.5);
    }
  }, [animation, actions, mixer.stats.actions.inUse]);  

  const lerpMorphTarget = (target, value, speed = 0.1) => {
    scene.traverse((child) => {
      if (child.isSkinnedMesh && child.morphTargetDictionary) {
        const index = child.morphTargetDictionary[target];
        if (
          index === undefined ||
          child.morphTargetInfluences[index] === undefined
        ) {
          return;
        }
        child.morphTargetInfluences[index] = THREE.MathUtils.lerp(
          child.morphTargetInfluences[index],
          value,
          speed
        );

        if (!setupMode) {
          try {
            set({
              [target]: value,
            });
          } catch (e) {}
        }
      }
    });
  };

  const [blink, setBlink] = useState(false);
  const [winkLeft, setWinkLeft] = useState(false);
  const [winkRight, setWinkRight] = useState(false);
  const [facialExpression, setFacialExpression] = useState("");
  const [audio, setAudio] = useState();

  useFrame(() => {
    !setupMode &&
      Object.keys(nodes.EyeLeft.morphTargetDictionary).forEach((key) => {
        const mapping = facialExpressions[facialExpression];
        if (key === "eyeBlinkLeft" || key === "eyeBlinkRight") {
          return; // eyes wink/blink are handled separately
        }
        if (mapping && mapping[key]) {
          lerpMorphTarget(key, mapping[key], 0.1);
        } else {
          lerpMorphTarget(key, 0, 0.1);
        }
      });

    lerpMorphTarget("eyeBlinkLeft", blink || winkLeft ? 1 : 0, 0.5);
    lerpMorphTarget("eyeBlinkRight", blink || winkRight ? 1 : 0, 0.5);

    // LIPSYNC
    if (setupMode) {
      return;
    }

    const appliedMorphTargets = [];
    if (message && lipsync) {
      const currentAudioTime = audio.currentTime;
      for (let i = 0; i < lipsync.mouthCues.length; i++) {
        const mouthCue = lipsync.mouthCues[i];
        if (
          currentAudioTime >= mouthCue.start &&
          currentAudioTime <= mouthCue.end
        ) {
          appliedMorphTargets.push(corresponding[mouthCue.value]);
          lerpMorphTarget(corresponding[mouthCue.value], 1, 0.2);
          break;
        }
      }
    }

    Object.values(corresponding).forEach((value) => {
      if (appliedMorphTargets.includes(value)) {
        return;
      }
      lerpMorphTarget(value, 0, 0.1);
    });
  });

  useControls("FacialExpressions", {
    chat: button(() => chat()),
    winkLeft: button(() => {
      setWinkLeft(true);
      setTimeout(() => setWinkLeft(false), 300);
    }),
    winkRight: button(() => {
      setWinkRight(true);
      setTimeout(() => setWinkRight(false), 300);
    }),
    animation: {
      value: animation,
      options: animations.map((a) => a.name),
      onChange: (value) => setAnimation(value),
    },
    facialExpression: {
      options: Object.keys(facialExpressions),
      onChange: (value) => setFacialExpression(value),
    },
    enableSetupMode: button(() => {
      setupMode = true;
    }),
    disableSetupMode: button(() => {
      setupMode = false;
    }),
    logMorphTargetValues: button(() => {
      const emotionValues = {};
      Object.keys(nodes.EyeLeft.morphTargetDictionary).forEach((key) => {
        if (key === "eyeBlinkLeft" || key === "eyeBlinkRight") {
          return; // eyes wink/blink are handled separately
        }
        const value =
          nodes.EyeLeft.morphTargetInfluences[
            nodes.EyeLeft.morphTargetDictionary[key]
          ];
        if (value > 0.01) {
          emotionValues[key] = value;
        }
      });
      console.log(JSON.stringify(emotionValues, null, 2));
    }),
  });

  const [, set] = useControls("MorphTarget", () =>
    Object.assign(
      {},
      ...Object.keys(nodes.EyeLeft.morphTargetDictionary).map((key) => {
        return {
          [key]: {
            label: key,
            value: 0,
            min: nodes.EyeLeft.morphTargetInfluences[
              nodes.EyeLeft.morphTargetDictionary[key]
            ],
            max: 1,
            onChange: (val) => {
              if (setupMode) {
                lerpMorphTarget(key, val, 1);
              }
            },
          },
        };
      })
    )
  );

  useEffect(() => {
    let blinkTimeout;
    const nextBlink = () => {
      blinkTimeout = setTimeout(() => {
        setBlink(true);
        setTimeout(() => {
          setBlink(false);
          nextBlink();
        }, 200);
      }, THREE.MathUtils.randInt(1000, 5000));
    };
    nextBlink();
    return () => clearTimeout(blinkTimeout);
  }, []);

  return (
    <group {...props} dispose={null}>
      <skinnedMesh
        name="EyeLeft"
        geometry={nodes.EyeLeft.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeLeft.skeleton}
        morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
      />
      <skinnedMesh
        name="EyeRight"
        geometry={nodes.EyeRight.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeRight.skeleton}
        morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Body.geometry}
        material={materials.Wolf3D_Body}
        skeleton={nodes.Wolf3D_Body.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
        material={materials.Wolf3D_Outfit_Bottom}
        skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
        material={materials.Wolf3D_Outfit_Footwear}
        skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Top.geometry}
        material={materials.Wolf3D_Outfit_Top}
        skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
      />
      <skinnedMesh
        name="Wolf3D_Teeth"
        geometry={nodes.Wolf3D_Teeth.geometry}
        material={materials.Wolf3D_Teeth}
        skeleton={nodes.Wolf3D_Teeth.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
      />
      <primitive object={nodes.Hips} />
      <primitive object={nodes.neutral_bone} />
      <skinnedMesh
        name="Wolf3D_Head_1"
        geometry={nodes.Wolf3D_Head_1.geometry}
        material={materials.Wolf3D_Skin}
        skeleton={nodes.Wolf3D_Head_1.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head_1.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head_1.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head_2"
        geometry={nodes.Wolf3D_Head_2.geometry}
        material={materials["Material.010"]}
        skeleton={nodes.Wolf3D_Head_2.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head_2.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head_2.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head_3"
        geometry={nodes.Wolf3D_Head_3.geometry}
        material={materials["Material.035"]}
        skeleton={nodes.Wolf3D_Head_3.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head_3.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head_3.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head_4"
        geometry={nodes.Wolf3D_Head_4.geometry}
        material={materials["Material.001"]}
        skeleton={nodes.Wolf3D_Head_4.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head_4.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head_4.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head_5"
        geometry={nodes.Wolf3D_Head_5.geometry}
        material={materials["Material.006"]}
        skeleton={nodes.Wolf3D_Head_5.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head_5.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head_5.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head_6"
        geometry={nodes.Wolf3D_Head_6.geometry}
        material={materials["Material.005"]}
        skeleton={nodes.Wolf3D_Head_6.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head_6.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head_6.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head_7"
        geometry={nodes.Wolf3D_Head_7.geometry}
        material={materials["Material.004"]}
        skeleton={nodes.Wolf3D_Head_7.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head_7.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head_7.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head_8"
        geometry={nodes.Wolf3D_Head_8.geometry}
        material={materials["Material.017"]}
        skeleton={nodes.Wolf3D_Head_8.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head_8.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head_8.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head_9"
        geometry={nodes.Wolf3D_Head_9.geometry}
        material={materials["Material.019"]}
        skeleton={nodes.Wolf3D_Head_9.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head_9.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head_9.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head_10"
        geometry={nodes.Wolf3D_Head_10.geometry}
        material={materials["Material.021"]}
        skeleton={nodes.Wolf3D_Head_10.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head_10.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head_10.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head_11"
        geometry={nodes.Wolf3D_Head_11.geometry}
        material={materials["Material.018"]}
        skeleton={nodes.Wolf3D_Head_11.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head_11.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head_11.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head_12"
        geometry={nodes.Wolf3D_Head_12.geometry}
        material={materials["Material.034"]}
        skeleton={nodes.Wolf3D_Head_12.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head_12.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head_12.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head_13"
        geometry={nodes.Wolf3D_Head_13.geometry}
        material={materials["Material.033"]}
        skeleton={nodes.Wolf3D_Head_13.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head_13.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head_13.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head_14"
        geometry={nodes.Wolf3D_Head_14.geometry}
        material={materials["Material.032"]}
        skeleton={nodes.Wolf3D_Head_14.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head_14.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head_14.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head_15"
        geometry={nodes.Wolf3D_Head_15.geometry}
        material={materials["Material.009"]}
        skeleton={nodes.Wolf3D_Head_15.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head_15.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head_15.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head_16"
        geometry={nodes.Wolf3D_Head_16.geometry}
        material={materials.hair1}
        skeleton={nodes.Wolf3D_Head_16.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head_16.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head_16.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head_17"
        geometry={nodes.Wolf3D_Head_17.geometry}
        material={materials["Material.031"]}
        skeleton={nodes.Wolf3D_Head_17.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head_17.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head_17.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head_18"
        geometry={nodes.Wolf3D_Head_18.geometry}
        material={materials["Material.030"]}
        skeleton={nodes.Wolf3D_Head_18.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head_18.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head_18.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head_19"
        geometry={nodes.Wolf3D_Head_19.geometry}
        material={materials["Material.029"]}
        skeleton={nodes.Wolf3D_Head_19.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head_19.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head_19.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head_20"
        geometry={nodes.Wolf3D_Head_20.geometry}
        material={materials["Material.036"]}
        skeleton={nodes.Wolf3D_Head_20.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head_20.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head_20.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head_21"
        geometry={nodes.Wolf3D_Head_21.geometry}
        material={materials["Material.028"]}
        skeleton={nodes.Wolf3D_Head_21.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head_21.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head_21.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head_22"
        geometry={nodes.Wolf3D_Head_22.geometry}
        material={materials["Material.012"]}
        skeleton={nodes.Wolf3D_Head_22.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head_22.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head_22.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head_23"
        geometry={nodes.Wolf3D_Head_23.geometry}
        material={materials["Material.016"]}
        skeleton={nodes.Wolf3D_Head_23.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head_23.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head_23.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head_24"
        geometry={nodes.Wolf3D_Head_24.geometry}
        material={materials["Material.014"]}
        skeleton={nodes.Wolf3D_Head_24.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head_24.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head_24.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head_25"
        geometry={nodes.Wolf3D_Head_25.geometry}
        material={materials["Material.020"]}
        skeleton={nodes.Wolf3D_Head_25.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head_25.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head_25.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head_26"
        geometry={nodes.Wolf3D_Head_26.geometry}
        material={materials["Material.011"]}
        skeleton={nodes.Wolf3D_Head_26.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head_26.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head_26.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head_27"
        geometry={nodes.Wolf3D_Head_27.geometry}
        material={materials["Material.013"]}
        skeleton={nodes.Wolf3D_Head_27.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head_27.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head_27.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head_28"
        geometry={nodes.Wolf3D_Head_28.geometry}
        material={materials["Material.027"]}
        skeleton={nodes.Wolf3D_Head_28.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head_28.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head_28.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head_29"
        geometry={nodes.Wolf3D_Head_29.geometry}
        material={materials["Material.015"]}
        skeleton={nodes.Wolf3D_Head_29.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head_29.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head_29.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head_30"
        geometry={nodes.Wolf3D_Head_30.geometry}
        material={materials["Material.026"]}
        skeleton={nodes.Wolf3D_Head_30.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head_30.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head_30.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head_31"
        geometry={nodes.Wolf3D_Head_31.geometry}
        material={materials["Material.025"]}
        skeleton={nodes.Wolf3D_Head_31.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head_31.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head_31.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head_32"
        geometry={nodes.Wolf3D_Head_32.geometry}
        material={materials["Material.024"]}
        skeleton={nodes.Wolf3D_Head_32.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head_32.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head_32.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head_33"
        geometry={nodes.Wolf3D_Head_33.geometry}
        material={materials["Material.008"]}
        skeleton={nodes.Wolf3D_Head_33.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head_33.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head_33.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head_34"
        geometry={nodes.Wolf3D_Head_34.geometry}
        material={materials["Material.022"]}
        skeleton={nodes.Wolf3D_Head_34.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head_34.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head_34.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head_35"
        geometry={nodes.Wolf3D_Head_35.geometry}
        material={materials["Material.023"]}
        skeleton={nodes.Wolf3D_Head_35.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head_35.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head_35.morphTargetInfluences}
      />
    </group>
  );
}

useGLTF.preload("/models/64f1a714fe61576b46f27ca2.glb");
useGLTF.preload("/models/animations.glb");
